DO NOT MERGE: DPE-3735 Add how-to guide for alert integration
canonical/kafka-operator pull request #178
Opened 2024-03-13 08:33 UTC by Batalex

TODO:

- [ ] Add mention of alert syncing with repo to remove rules
- [ ] Check the mystery question

2024-03-13 08:40 UTC, Batalex commented on docs/how-to/h-integrate-alerts.md
> +The rest of this guide works on the assumption that two models are deployed: `cos` (on k8s) containing the cos-lite bundle and `kafka-dev` (on VM **TODO: adapt for k8s version**) containing 5 Zookeep
There should not be any difference between VM and k8s for the rest of the guide. The `grafana-agent` subordinate charm is mentioned in the Enable Monitoring guide

2024-03-14 07:16 UTC, deusebio requested changes
Great job! I liked the reading and it was actually simpler than expected (TWIL). I have one main suggestions which is to make it more like an how-to than a tutorial. Right now it feels a bit like a tutorial. There are few things we can probably do:

1. Use placeholder instead of concrete names
2. Move the examples to a separate place (I'm suggesting to create one branch in our kafka-test-app charm) and first state what they need to do, THEN provide them examples if they are interested to know more. 
3. Change the structure from a storyline and a specific use-case, to just provide the user what they need to custome their alerting rules/dashboard, in a concise manner. To this end, I believe it makes it more a how-to to rework slightly the structure, like:

    * Create Repo
    * Deploy cos-configuration-k8s (in a general way, without specifying either alert rules or dahsboards paths)
    * Configure and Relate:
        * alert rules
        * dashboards
        (alert rules and dashboards should feel like two non-mutually exclusive but optional items, with the same dignity)

2024-03-14 08:31 UTC, Batalex commented on docs/how-to/h-integrate-alerts.md
> +To keep things simple, we will illustrate this guide with a single alert rule that Prometheus will fire if our Kafka cluster does not achieve high availability.
PR created: https://github.com/canonical/kafka-test-app/pull/16

2024-03-14 09:07 UTC, Batalex commented on docs/how-to/h-integrate-alerts.md
> +To keep things simple, we will illustrate this guide with a single alert rule that Prometheus will fire if our Kafka cluster does not achieve high availability.
With those suggestions, the guide is more concise and to-the-point, thank you.

2024-03-18 13:39 UTC, deusebio approved these changes
Looks good! When also @zmraul is happy, we can just update Discourse, and let Gatekeeper to raise the PR, closing this one referencing the automatically created one

2024-03-18 16:26 UTC, zmraul approved these changes
Very nice! TIL :)

2024-03-19 08:23 UTC, Batalex commented
Thank you both for your review, the docs are live for both VM and K8s!

2024-03-19 08:23 UTC, closed without merging